### ISSUE TITLE
String in an expression that produces an annotation gives an error

### ISSUE THREAD

**Issue by hroskes** [PyCQA/pyflakes#611]
These cases don't work in 2.2.0:

```
a: "string"[:4]

def f(x): return {"string": str}[x]
b: f("string")
```

**Comment by asottile** [comment]
those are invalid PEP 484 type annotations and therefore mypy will raise an error about them and therefore pyflakes will raise an error about them:

```console
$ mypy t.py
t.py:1: error: syntax error in type comment
Found 1 error in 1 file (checked 1 source file)
```

did you mean `a = "string"[:4]` and `b = f("string")`

**Comment by hroskes** [comment]
I'm sorry I'm not getting it.  Does the type annotation actually have to be explicitly a type or string, rather than an expression that returns a type or string?

In that case, this should give an error too:
```
ing = None
string = None

a: "str"
b: "string"
c: "str" + "ing"
```
but I'm only getting an error from pyflakes if I comment out the ing = None line.

**Comment by asottile** [comment]
see [acceptable type hints](https://www.python.org/dev/peps/pep-0484/#acceptable-type-hints) -- a quoted type name is a [forward reference](https://www.python.org/dev/peps/pep-0484/#forward-references)

an expression is not statically computable so it is not allowed

**Comment by hroskes** [comment]
ok, but then my previous example should give an error whether or not `ing` is defined.

**Comment by asottile** [comment]
pyflakes assumes strings in annotations are forward annotations

**Comment by hroskes** [comment]
So... it's ok to have an expression, as long as all strings in it are existing variables?  That seems very convoluted to me.

**Comment by asottile** [comment]
it's not ok to have an expression:

```
$ mypy t.py
t.py:5: error: Variable "t.string" is not valid as a type
t.py:5: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
t.py:6: error: Invalid type comment or annotation
Found 2 errors in 1 file (checked 1 source file)
```
