### ISSUE TITLE
F811 incorrectly raised for type annotation of imported variable

### ISSUE THREAD

**Issue by mick88** [PyCQA/pyflakes#617]
The following piece of code raises F811 error in pyflakes 2.3.0:
```python
        from django.core.files.storage import default_storage
        default_storage: Storage
        file_path = os.path.join(constants.FILE_FIELD_UPLOAD_DIR_NAME, value.name)
        value = default_storage.save(file_path, value)
```

I am using pyflakes with flake8 and getting this output:
```
F811 redefinition of unused 'default_storage' from line 124
        default_storage: Storage
        ^
1     F811 redefinition of unused 'default_storage' from line 124
```

the code works correctly and `default_storage: Storage` does not redefine the variable, and `default_storage` is used two lines below.

**Comment by asottile** [comment]
can confirm -- looks like a slight regression in #535 (which introduces annotated-assignments without values as types-only bindings) -- probably need to special case this particular situation of an annotation-only assignment of an imported name

**Comment by henzef** [comment]
I think I have another example for this:
    gvar: int

    def set_var():
        global gvar
        gvar = 1
    
    def print_var():
        print(gvar)
    
    set_var()
    print_var()

Which seems to be the same bug. Or should I open a separate issue?

**Comment by asottile** [comment]
@henzef that's unrelated and covered in #621
