### ISSUE TITLE
F811 redefinition of unused line detection has changed between pyflakes 2.0.0 and 2.1.0 ? 

### ISSUE THREAD

**Issue by Nairwolf** [PyCQA/pyflakes#432]
Hello, 

I've updated my linter from pyflakes 2.0.0 to pyflakes 2.1.0 and I see a breaking changes no documented anywhere. Is this change was wanted, or not, that's the real question. 

With pytest, it's usual to have a file like that.
```
import pytest
from mylib import customfixture


@pytest.fixture(scope="session")
def ctx(customfixture):
    pass
```

With pyflakes 2.0.0, we have this behaviour: 

```
/ws # pyflakes --version
2.0.0
/ws # pyflakes mock.py 
mock.py:2: 'mylib.customfixture' imported but unused
mock.py:5: redefinition of unused 'customfixture' from line 2
```

So the "redefinition of unused" is detected at line 5.

With pyflakes 2.1.0, we have this behaviour:

```
/ws # pyflakes --version
2.1.0 Python 3.7.2 on Linux
/ws # pyflakes mock.py
mock.py:2: 'mylib.customfixture' imported but unused
mock.py:6: redefinition of unused 'customfixture' from line 2
```

Is it a breaking change intended or not ? I don't see in the release notes of 2.1.0 what caused this change.

**Comment by asottile** [comment]
I wouldn't call it a _breaking change_ per se as there's no api guarantees around lint errors and messages.  In fact, it looks like a bug **fix** to me, the original error pointed at the decorator (which is nonsense).  Here's the change that fixed this (ignore `bad` / `good` -- that's just what bisect refers to them as)

```
$ git bisect good 2.0.0
$ git bisect bad 2.1.0
$ git bisect run bash -c 'python3 -mpyflakes t.py | grep :5:'
running bash -c python3 -mpyflakes t.py | grep :5:
Bisecting: 8 revisions left to test after this (roughly 3 steps)
[f9afd2b04f98116fde647a60aed310114768d179] test_errors_syntax: Expect SystemExit error code 1
running bash -c python3 -mpyflakes t.py | grep :5:
Bisecting: 3 revisions left to test after this (roughly 2 steps)
[d6f54c33f428d19d5bcd4c67e9ff89572a85c1c5] Recognize __module__ when used in class scope
running bash -c python3 -mpyflakes t.py | grep :5:
t.py:5: redefinition of unused 'customfixture' from line 2
Bisecting: 1 revision left to test after this (roughly 1 step)
[fb1f223ac2141772f140be6f1108d02009c1d658] checker.py: Handle UnboundLocal error for builtins
running bash -c python3 -mpyflakes t.py | grep :5:
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[9dd73ec54411a563410872b47e76f0f89f34ecfe] Handle subtrees as input to checker
running bash -c python3 -mpyflakes t.py | grep :5:
9dd73ec54411a563410872b47e76f0f89f34ecfe is the first bad commit
commit 9dd73ec54411a563410872b47e76f0f89f34ecfe
Author: MacBox7 <ajankit2304@gmail.com>
Date:   Wed Jun 27 19:43:10 2018 +0530

    Handle subtrees as input to checker
    
    This patch essentially adds the the
    functionality for the Checker to handle
    subtrees. Along with this args have also
    been parsed through handlers.
    
    Closes https://github.com/PyCQA/pyflakes/issues/338

:040000 040000 a021f091c7ec5edba26a3607af5156e2a8d98ba4 59bccb608ec24f84b504ff8901ba13c639c75ef6 M	pyflakes
bisect run success
```

**Comment by Nairwolf** [comment]
Thank you to confirm me it was a bug fix. I just wanted to know if this change was intended or not, since it's not announced in the release note. 

Thank you for the confirmation.

**Comment by asottile** [comment]
doesn't seem intentional, but it is a nice side-effect of that change :man_shrugging:
